--TABELA VESTIBULAR

SELECT * FROM st_vestibular

--VIEWS

SELECT * FROM VW_ST_CANDIDATO

SELECT * FROM VW_ST_CURSO

SELECT * FROM VW_ST_FORMA_PAGTO

SELECT * FROM VW_ST_INSCRICOES

SELECT * FROM VW_ST_INSCRICOES_PAGAS

SELECT * FROM VW_ST_PREINSCRICOES

SELECT * FROM VW_ST_PROCESSO