--DIMENSOES

SELECT * FROM DIM_CANDIDATO

SELECT * FROM DIM_CURSO

SELECT * FROM DIM_DATA

SELECT * FROM DIM_FORMA_PAGTO

SELECT * FROM DIM_HORA

SELECT * FROM DIM_PROCESSO

--TABELAS FATO

SELECT * FROM FATO_PRE_INSCRICOES

SELECT * FROM FATO_INSCRICOES

SELECT * FROM FATO_INSCRICOES_PAGA